-- Working SNOWFLAKE SAMLE DATA TPCH_SF1.CUSTOMER & TABLE CREATION 


SHOW DATABASES;
USE demo_db;

Desc CUSTOMER
SELECT COUNT(*) FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER

/* Copy all those 8 TABLES from Database with Schema - NOWFLAKE_SAMPLE_DATA.TPCH_SF1 to DEMO_DB.PUBLIC */

Show tables;
Create table Customer
AS
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER

Create table Lineitem
AS
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.Lineitem

Create table Nation
AS
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.NATION


Create table Orders
AS
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS

Create table Part
AS
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.PART

Create table Partsupp
AS
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.PARTSUPP

Create table Region
AS
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.REGION

Create table Supplier
AS
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.SUPPLIER

show tables;
SELECT COUNT(*) FROM DEMO_DB.PUBLIC.CUSTOMER
SELECT COUNT(*) FROM DEMO_DB.PUBLIC.LINEITEM
SELECT COUNT(*) FROM DEMO_DB.PUBLIC.NATION
SELECT COUNT(*) FROM DEMO_DB.PUBLIC.ORDERS
SELECT COUNT(*) FROM DEMO_DB.PUBLIC.PART
SELECT COUNT(*) FROM DEMO_DB.PUBLIC.PARTSUPP
SELECT COUNT(*) FROM DEMO_DB.PUBLIC.REGION
SELECT COUNT(*) FROM DEMO_DB.PUBLIC.SUPPLIER

SELECT 'CUSTOMER' AS table_name, COUNT(*) AS row_count FROM DEMO_DB.PUBLIC.CUSTOMER
UNION ALL
SELECT 'LINEITEM', COUNT(*) FROM DEMO_DB.PUBLIC.LINEITEM
UNION ALL
SELECT 'NATION', COUNT(*) FROM DEMO_DB.PUBLIC.NATION
UNION ALL
SELECT 'ORDERS', COUNT(*) FROM DEMO_DB.PUBLIC.ORDERS
UNION ALL
SELECT 'PART', COUNT(*) FROM DEMO_DB.PUBLIC.PART
UNION ALL
SELECT 'PARTSUPP', COUNT(*) FROM DEMO_DB.PUBLIC.PARTSUPP
UNION ALL
SELECT 'REGION', COUNT(*) FROM DEMO_DB.PUBLIC.REGION
UNION ALL
SELECT 'SUPPLIER', COUNT(*) FROM DEMO_DB.PUBLIC.SUPPLIER;

SELECT COUNT(*) FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER
SELECT COUNT(*) FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.LINEITEM
SELECT COUNT(*) FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.NATION
SELECT COUNT(*) FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS
SELECT COUNT(*) FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.PART
SELECT COUNT(*) FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.PARTSUPP
SELECT COUNT(*) FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.REGION
SELECT COUNT(*) FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.SUPPLIER

SELECT 'CUSTOMER' AS table_name, COUNT(*) AS row_count FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER
UNION ALL
SELECT 'LINEITEM', COUNT(*) FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.LINEITEM
UNION ALL
SELECT 'NATION', COUNT(*) FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.NATION
UNION ALL
SELECT 'ORDERS', COUNT(*) FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS
UNION ALL
SELECT 'PART', COUNT(*) FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.PART
UNION ALL
SELECT 'PARTSUPP', COUNT(*) FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.PARTSUPP
UNION ALL
SELECT 'REGION', COUNT(*) FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.REGION
UNION ALL
SELECT 'SUPPLIER', COUNT(*) FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.SUPPLIER

/* This performs COUNT Opertions for 8 tables with two different Databases & Schemas */

SELECT 
    'CUSTOMER' AS table_name,
    (SELECT COUNT(*) FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER) AS COUNT_SNOWFLAKE_SAMPLE,
    (SELECT COUNT(*) FROM DEMO_DB.PUBLIC.CUSTOMER) AS COUNT_DEMO_DB

UNION ALL

SELECT 
    'LINEITEM',
    (SELECT COUNT(*) FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.LINEITEM),
    (SELECT COUNT(*) FROM DEMO_DB.PUBLIC.LINEITEM)

UNION ALL

SELECT 
    'NATION',
    (SELECT COUNT(*) FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.NATION),
    (SELECT COUNT(*) FROM DEMO_DB.PUBLIC.NATION)

UNION ALL

SELECT 
    'ORDERS',
    (SELECT COUNT(*) FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS),
    (SELECT COUNT(*) FROM DEMO_DB.PUBLIC.ORDERS)

UNION ALL

SELECT 
    'PART',
    (SELECT COUNT(*) FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.PART),
    (SELECT COUNT(*) FROM DEMO_DB.PUBLIC.PART)

UNION ALL

SELECT 
    'PARTSUPP',
    (SELECT COUNT(*) FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.PARTSUPP),
    (SELECT COUNT(*) FROM DEMO_DB.PUBLIC.PARTSUPP)

UNION ALL

SELECT 
    'REGION',
    (SELECT COUNT(*) FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.REGION),
    (SELECT COUNT(*) FROM DEMO_DB.PUBLIC.REGION)

UNION ALL

SELECT 
    'SUPPLIER',
    (SELECT COUNT(*) FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.SUPPLIER),
    (SELECT COUNT(*) FROM DEMO_DB.PUBLIC.SUPPLIER);

/* Now CHANGE DATABASE NAME : DEMO_DB TO OUR_FIRST_DEMO_DB.*/

ALTER DATABASE DEMO_DB RENAME TO OUR_FIRST_DEMO_DB

SHOW DATABASES