-- JSON DATA INTO SNOWFLAKE - MANAGE_DB DATABASE

// First step: Load Raw JSON
USE MANAGE_DB;

LIST @MANAGE_DB.EXTERNAL_STAGES.JSONSTAGE;

CREATE OR REPLACE stage MANAGE_DB.EXTERNAL_STAGES.JSONSTAGE
     url='s3://bucketsnowflake-jsondemo';

CREATE OR REPLACE file format MANAGE_DB.FILE_FORMATS.JSONFORMAT
    TYPE = JSON;
    
-- CREATE TABLE for JSON DATA.    
CREATE OR REPLACE table MANAGE_DB.PUBLIC.JSON_RAW (
    raw_file variant);
    
-- View the records befor loading JSON DATA
SELECT COUNT(*) FROM MANAGE_DB.PUBLIC.JSON_RAW;

-- Now load JSON data to MANAGE_DB.PUBLIC.JSON_RAW Table.
COPY INTO MANAGE_DB.PUBLIC.JSON_RAW
    FROM @MANAGE_DB.EXTERNAL_STAGES.JSONSTAGE
    file_format= MANAGE_DB.FILE_FORMATS.JSONFORMAT
    files = ('HR_data.json');
    
-- View the records After loading JSON DATA
SELECT COUNT(*) FROM MANAGE_DB.PUBLIC.JSON_RAW;
SELECT * FROM MANAGE_DB.PUBLIC.JSON_RAW;

SELECT edition
  FROM SNOWFLAKE.ORGANIZATION_USAGE.ACCOUNTS
  WHERE account_name = CURRENT_ACCOUNT();