/* Script to Generate the COUNT for SAME TABLES, But different Databases & Schema +/


SELECT 
    'CUSTOMER' AS table_name,
    (SELECT COUNT(*) FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER) AS COUNT_SNOWFLAKE_SAMPLE,
    (SELECT COUNT(*) FROM DEMO_DB.PUBLIC.CUSTOMER) AS COUNT_DEMO_DB

UNION ALL

SELECT 
    'LINEITEM',
    (SELECT COUNT(*) FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.LINEITEM),
    (SELECT COUNT(*) FROM DEMO_DB.PUBLIC.LINEITEM)

UNION ALL

SELECT 
    'NATION',
    (SELECT COUNT(*) FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.NATION),
    (SELECT COUNT(*) FROM DEMO_DB.PUBLIC.NATION)

UNION ALL

SELECT 
    'ORDERS',
    (SELECT COUNT(*) FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS),
    (SELECT COUNT(*) FROM DEMO_DB.PUBLIC.ORDERS)

UNION ALL

SELECT 
    'PART',
    (SELECT COUNT(*) FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.PART),
    (SELECT COUNT(*) FROM DEMO_DB.PUBLIC.PART)

UNION ALL

SELECT 
    'PARTSUPP',
    (SELECT COUNT(*) FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.PARTSUPP),
    (SELECT COUNT(*) FROM DEMO_DB.PUBLIC.PARTSUPP)

UNION ALL

SELECT 
    'REGION',
    (SELECT COUNT(*) FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.REGION),
    (SELECT COUNT(*) FROM DEMO_DB.PUBLIC.REGION)

UNION ALL

SELECT 
    'SUPPLIER',
    (SELECT COUNT(*) FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.SUPPLIER),
    (SELECT COUNT(*) FROM DEMO_DB.PUBLIC.SUPPLIER);

