SELECT CURRENT_ACCOUNT_LOCATOR();
SELECT CURRENT_ACCOUNT_NAME();
SELECT CURRENT_USER();
SELECT CURRENT_ROLE();

SELECT CURRENT_ACCOUNT_LOCATOR(),CURRENT_ACCOUNT_NAME(), CURRENT_USER()

SELECT CURRENT_ORGANIZATION_NAME() || '-' || CURRENT_ACCOUNT_NAME();